version: '3'
services:
  qdrant:
    container_name: llama-search-qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_llama_search_data:/qdrant/storage:z
    networks:
      - backend
networks:
  backend: 
    name: llama-network

volumes:
  qdrant_llama_search_data:
  

